#include "catch.hpp"

#include <dekaf2/util/qrcode/kqrcode.h>
#include <dekaf2/core/strings/kstring.h>
#include <vector>

using namespace dekaf2;

namespace {

// compare a forced-parameter QR code against a known-good reference matrix
// (one string per row, '1' = dark). The references were generated by an
// independent, spec-conformant encoder and decode correctly.
bool MatchesReference(KStringView sData, KQRCode::ECC Ecc, uint8_t iVersion, int8_t iMask,
                      const std::vector<KString>& Expected)
{
	KQRCode qr(sData, Ecc, iVersion, iVersion, iMask);
	if (qr.empty() || qr.Size() != Expected.size()) return false;
	for (uint16_t y = 0; y < qr.Size(); ++y)
	{
		if (Expected[y].size() != qr.Size()) return false;
		for (uint16_t x = 0; x < qr.Size(); ++x)
		{
			bool bExpected = (Expected[y][x] == '1');
			if (qr.Module(x, y) != bExpected) return false;
		}
	}
	return true;
}

} // anonymous namespace

TEST_CASE("KQRCode")
{
	SECTION("size, version and emptiness")
	{
		KQRCode qr("hello, world", KQRCode::ECC::Medium);
		CHECK ( !qr.empty() );
		CHECK ( qr.Size() == 4 * qr.Version() + 17 );
		CHECK ( qr.Version() >= 1 );

		// a string that cannot fit even version 40 at High ECC must be empty()
		KString sHuge(4000, 'x');
		KQRCode big(sHuge, KQRCode::ECC::High);
		CHECK ( big.empty() );
		CHECK ( big.Size() == 0 );
	}

	SECTION("encoding is deterministic")
	{
		KQRCode a("https://example.com/abc", KQRCode::ECC::Quartile);
		KQRCode b("https://example.com/abc", KQRCode::ECC::Quartile);
		REQUIRE ( a.Size() == b.Size() );
		CHECK ( a.MaskPattern() == b.MaskPattern() );
		bool bSame = true;
		for (uint16_t y = 0; y < a.Size(); ++y)
			for (uint16_t x = 0; x < a.Size(); ++x)
				if (a.Module(x, y) != b.Module(x, y)) bSame = false;
		CHECK ( bSame );
	}

	SECTION("finder patterns sit in the three corners")
	{
		KQRCode qr("finder pattern check", KQRCode::ECC::Medium);
		REQUIRE ( !qr.empty() );
		uint16_t n = qr.Size();
		auto finderOK = [&](uint16_t ox, uint16_t oy)
		{
			return qr.Module(ox + 0, oy + 0) && qr.Module(ox + 6, oy + 0)   // top corners dark
			    && qr.Module(ox + 0, oy + 6) && qr.Module(ox + 6, oy + 6)   // bottom corners dark
			    && !qr.Module(ox + 1, oy + 1) && !qr.Module(ox + 5, oy + 5) // inner ring light
			    && qr.Module(ox + 3, oy + 3);                               // 3x3 core dark
		};
		CHECK ( finderOK(0, 0)     ); // top-left
		CHECK ( finderOK(n - 7, 0) ); // top-right
		CHECK ( finderOK(0, n - 7) ); // bottom-left
	}

	SECTION("SVG and text rendering are well formed")
	{
		KQRCode qr("render me", KQRCode::ECC::Low);
		KString sSVG = qr.ToSVG(4, 3);
		CHECK ( sSVG.starts_with("<?xml") );
		CHECK ( sSVG.contains("<svg") );
		CHECK ( sSVG.contains("</svg>") );

		KString sTxt = qr.ToText(2);
		CHECK ( !sTxt.empty() );
		CHECK ( sTxt.contains('\n') );
	}

	// Exact-match checks against independently generated, decodable reference
	// codes. Version 1 (no alignment), version 2 (one alignment pattern) and
	// version 7 (which also carries BCH version-info modules) are covered.
	SECTION("matches reference matrices")
	{
		// 'HELLO'  ECC M  version 1  mask 4
		static const std::vector<KString> REF_V1_M = {
			"111111101101001111111", "100000100110101000001", "101110100111101011101",
			"101110101001001011101", "101110101000101011101", "100000101011001000001",
			"111111101010101111111", "000000001111100000000", "100010111111011111001",
			"000111001011100101111", "101100101011001110010", "111001000100011010000",
			"001011100100111000110", "000000001110111001011", "111111101100110001010",
			"100000100001100100010", "101110101001001110101", "101110100001100001011",
			"101110100111001111000", "100000100100011000000", "111111101000111110101",
		};
		// 'kssod-test'  ECC Q  version 2  mask 3
		static const std::vector<KString> REF_V2_Q = {
			"1111111000110001101111111", "1000001010000011001000001", "1011101010000111001011101",
			"1011101000111000101011101", "1011101000111100001011101", "1000001001011010001000001",
			"1111111010101010101111111", "0000000001000110000000000", "0111011001100110100000110",
			"1100100000111001110101010", "0110101100100011000101100", "1010000100110111000101111",
			"0000001000001000101111101", "0110000100011000010111101", "0100111001100110011001010",
			"1000110100011101000100010", "0001001010111100111110111", "0000000011001010100011101",
			"1111111000101111101011011", "1000001011000101100010011", "1011101001000111111110001",
			"1011101010110101110010101", "1011101011111111110111010", "1000001010000101100101100",
			"1111111000001111011100111",
		};
		// 'version 7 exercises the BCH version-info modules'  ECC H  version 7  mask 2
		static const std::vector<KString> REF_V7_H = {
			"111111101101001001101111011111110100101111111", "100000101111111101110001100011010001001000001",
			"101110101100011110111001101110110101001011101", "101110100100100101111110001000100101101011101",
			"101110100111111001001111111001110111101011101", "100000101111101000111000101000100000001000001",
			"111111101010101010101010101010101010101111111", "000000001000010101101000110010000010100000000",
			"001110101101101100111111100111111110011100111", "011000010010011011000011110001101101111110101",
			"001000110100111101111010101110011111100011110", "000111010101000100010011001110101101100110101",
			"111111111110010111000010011001110100011001110", "100101011000010111011101010110110001110001100",
			"001010101000010010011110111111111011001010010", "100000010011110101110010101011001110100111111",
			"101011111111001000010000100110000000011000000", "111100010101000011000110000001010000110110111",
			"100010100001100101011011000000110111001000010", "000101000000110100011101000100101010110011110",
			"001111111001011110011111111011110100111110010", "110010001111011101001000101010100001100010011",
			"010110101011011010101010110001100111101010110", "100110001101000101001000110100100010100010100",
			"011011111010011000011111100101111111111110000", "011111001001010001100110001000001011010001000",
			"111001111010100011001011111101111101110001011", "010111001010001010010000000110100100011110101",
			"011000100000000011101011111100100101111010011", "101000010001010101010010010000011101011001001",
			"000110101001000010101100100000000011010110010", "000010010101010001011101010001001001001101001",
			"111000111011110000000111000111100100100000111", "100100000001001001100100100101001000010101100",
			"000010101011100100111001000000011110000001110", "011110010110010011100010000001101011010101101",
			"100110111010101000011111111101010010111111000", "000000001011011100111000101100100000100010101",
			"111111100011111010101010100110001111101011010", "100000100110001011111000101000001000100011100",
			"101110101010010111001111110100100000111110001", "101110101011011001010000010111011001001110111",
			"101110101011011100111110111111110011110000100", "100000100101100001110001011001010101110101100",
			"111111100100000111101110010101000001101101010",
		};

		CHECK ( MatchesReference("HELLO", KQRCode::ECC::Medium, 1, 4, REF_V1_M) );
		CHECK ( MatchesReference("kssod-test", KQRCode::ECC::Quartile, 2, 3, REF_V2_Q) );
		CHECK ( MatchesReference("version 7 exercises the BCH version-info modules",
		                         KQRCode::ECC::High, 7, 2, REF_V7_H) );
	}
}
