#!/bin/bash

# Writes three headers from the CLDR data in this directory:
#
# kcldr_plurals.h from plurals.json and ordinals.json: the plural rules of every
# language as C++ tables. The rule texts are split at their "@integer"/"@decimal"
# sample part: the rules go into this header for the library, the samples into
# ../../utests/kcldr_plural_samples.h for the unit tests, which the container
# suites build from utests/ alone. A binary that uses the rules never carries
# the samples.
#
# kcldr_likelysubtags.h from likelySubtags.json: the script of every language
# that is written in more than one script depending on the region ("zh" is
# Hans, "zh-TW" is Hant). Languages with one script get no rows.
#
# The script reads the JSON line by line. It relies on the fixed layout of the
# cldr-json files: one key per line, every value on the same line as its key,
# no escape sequences in the values. A line outside this layout stops the
# script, so that a changed layout is noticed instead of producing a wrong table.
#
# Needs bash 3.2 or later and sort. usage: generate.sh

# byte order for sort and byte semantics for the regular expressions
export LC_ALL=C

# separates the fields of the intermediate rows, cannot appear in the data
SEP=$'\x1f'

Die ()
{
	echo "${*} - abort" >&2
	exit 1
}

# removes leading and trailing whitespace from the text in the second argument
# and stores the result in the variable named by the first argument
Trim ()
{
	local TEXT="${2}"
	TEXT="${TEXT#"${TEXT%%[![:space:]]*}"}"
	TEXT="${TEXT%"${TEXT##*[![:space:]]}"}"
	printf -v "${1}" '%s' "${TEXT}"
}

# prints the value of a version field ("_cldrVersion", "_unicodeVersion") of a json file
Version ()
{
	local FILE="${1}" FIELD="${2}" LINE
	local RE="^[[:space:]]*\"${FIELD}\": \"([^\"]*)\",?\$"

	while IFS= read -r LINE; do
		if [[ "${LINE}" =~ ${RE} ]]; then
			echo "${BASH_REMATCH[1]}"
			return 0
		fi
	done < "${FILE}"

	Die "${FILE}: no field ${FIELD}"
}

# prints the header comment of a generated file
Preamble ()
{
	printf '// generated by from/cldr/generate.sh from CLDR %s (Unicode %s) - do not edit, run from/cldr/update.sh\n' "${CLDR_VERSION}" "${UNICODE_VERSION}"
	printf '// Data: Unicode CLDR, see LICENSE in this directory\n\n'
	printf '#pragma once\n\n'
}

# prints one row per plural rule of a json file: locale, category, rule, samples,
# separated by SEP. The rows are unsorted.
Rows ()
{
	local FILE="${1}" LINE LOCALE="" TEXT RULE SAMPLES
	local -i LINENUM=0
	local RE_OBJECT='^[[:space:]]*"([^"]+)": \{$'
	local RE_RULE='^[[:space:]]*"pluralRule-count-([a-z]+)": "([^"]*)",?$'
	local RE_VERSION='^[[:space:]]*"_[a-zA-Z]+": "[^"]*",?$'
	local RE_BRACE='^[[:space:]]*[{}],?$'

	while IFS= read -r LINE; do
		LINENUM+=1
		if [[ "${LINE}" =~ ${RE_RULE} ]]; then
			[[ -n "${LOCALE}" ]] || Die "${FILE}:${LINENUM}: rule outside of a locale object"
			TEXT="${BASH_REMATCH[2]}"
			[[ "${TEXT}" != *\\* ]] || Die "${FILE}:${LINENUM}: JSON escape sequences are not supported"
			# "i = 1 and v = 0 @integer 1 @decimal 1.0" -> "i = 1 and v = 0" and "@integer 1 @decimal 1.0"
			if [[ "${TEXT}" == *@* ]]; then
				Trim RULE    "${TEXT%%@*}"
				Trim SAMPLES "@${TEXT#*@}"
			else
				Trim RULE    "${TEXT}"
				SAMPLES=""
			fi
			printf '%s\n' "${LOCALE}${SEP}${BASH_REMATCH[1]}${SEP}${RULE}${SEP}${SAMPLES}"
		elif [[ "${LINE}" =~ ${RE_OBJECT} ]]; then
			# the innermost object before a rule line is its locale, the outer objects
			# ("supplemental", "version", "plurals-type-...") never contain rule lines
			LOCALE="${BASH_REMATCH[1]}"
		elif [[ "${LINE}" =~ ${RE_VERSION} || "${LINE}" =~ ${RE_BRACE} ]]; then
			:
		else
			Die "${FILE}:${LINENUM}: unexpected line: ${LINE}"
		fi
	done < "${FILE}"
}

# prints the C++ table NAMERules[] from sorted rows
RulesTable ()
{
	local NAME="${1}" ROWS="${2}" LOCALE CATEGORY RULE SAMPLES

	printf 'constexpr KCLDRPluralRule %sRules[] =\n{\n' "${NAME}"
	while IFS="${SEP}" read -r LOCALE CATEGORY RULE SAMPLES; do
		printf '\t{ "%s", "%s", "%s" },\n' "${LOCALE}" "${CATEGORY}" "${RULE}"
	done <<< "${ROWS}"
	printf '};\n\n'
}

# prints the C++ table NAMESamples[] from sorted rows
SamplesTable ()
{
	local NAME="${1}" ROWS="${2}" LOCALE CATEGORY RULE SAMPLES

	printf 'constexpr KCLDRPluralSample %sSamples[] =\n{\n' "${NAME}"
	while IFS="${SEP}" read -r LOCALE CATEGORY RULE SAMPLES; do
		printf '\t{ "%s", "%s", "%s" },\n' "${LOCALE}" "${CATEGORY}" "${SAMPLES}"
	done <<< "${ROWS}"
	printf '};\n\n'
}

# prints one row per entry of likelySubtags.json whose key is a language alone
# or a language with a region: language, region (empty for the language alone),
# script, separated by SEP. Entries for "und" (an unknown language) and entries
# whose key names a script are skipped. The rows are unsorted.
Likely ()
{
	local FILE="${1}" LINE KEY VALUE KL KR KX VL VS VR
	local -i LINENUM=0
	local RE_ENTRY='^[[:space:]]*"([a-zA-Z0-9-]+)": "([a-zA-Z0-9-]+)",?$'
	local RE_OBJECT='^[[:space:]]*"([^"]+)": \{$'
	local RE_VERSION='^[[:space:]]*"_[a-zA-Z]+": "[^"]*",?$'
	local RE_BRACE='^[[:space:]]*[{}],?$'
	local RE_SCRIPT='^[A-Z][a-z]{3}$'

	while IFS= read -r LINE; do
		LINENUM+=1
		if [[ "${LINE}" =~ ${RE_ENTRY} ]]; then
			KEY="${BASH_REMATCH[1]}"
			VALUE="${BASH_REMATCH[2]}"
			# "zh-TW": "zh-Hant-TW"
			IFS=- read -r KL KR KX <<< "${KEY}"
			IFS=- read -r VL VS VR <<< "${VALUE}"
			[[ "${VS}" =~ ${RE_SCRIPT} ]] || Die "${FILE}:${LINENUM}: no script in ${VALUE}"
			if [[ "${KL}" != "und" && -z "${KX}" && ! "${KR}" =~ ${RE_SCRIPT} ]]; then
				printf '%s\n' "${KL}${SEP}${KR}${SEP}${VS}"
			fi
		elif [[ "${LINE}" =~ ${RE_OBJECT} || "${LINE}" =~ ${RE_VERSION} || "${LINE}" =~ ${RE_BRACE} ]]; then
			:
		else
			Die "${FILE}:${LINENUM}: unexpected line: ${LINE}"
		fi
	done < "${FILE}"
}

# prints the C++ table kCLDRLikelyScripts[] from rows sorted by language and
# region, where the row of the language alone comes first: for every language
# that has a region with another script, the row of its default script (empty
# region) and the rows of the regions that differ
ScriptTable ()
{
	local ROWS="${1}" LANGUAGE REGION SCRIPT CURRENT="" DEFAULT="" EXCEPTIONS=""

	printf 'constexpr KCLDRLikelyScript kCLDRLikelyScripts[] =\n{\n'

	while IFS="${SEP}" read -r LANGUAGE REGION SCRIPT; do
		if [[ "${LANGUAGE}" != "${CURRENT}" ]]; then
			[[ -z "${EXCEPTIONS}" ]] || printf '\t{ "%s", "", "%s" },\n%s' "${CURRENT}" "${DEFAULT}" "${EXCEPTIONS}"
			[[ -z "${REGION}" ]] || Die "likelySubtags.json: ${LANGUAGE}-${REGION} without an entry for ${LANGUAGE} alone"
			CURRENT="${LANGUAGE}"
			DEFAULT="${SCRIPT}"
			EXCEPTIONS=""
		elif [[ "${SCRIPT}" != "${DEFAULT}" ]]; then
			EXCEPTIONS+=$'\t'"{ \"${LANGUAGE}\", \"${REGION}\", \"${SCRIPT}\" },"$'\n'
		fi
	done <<< "${ROWS}"

	[[ -z "${EXCEPTIONS}" ]] || printf '\t{ "%s", "", "%s" },\n%s' "${CURRENT}" "${DEFAULT}" "${EXCEPTIONS}"
	printf '};\n\n'
}

set -o pipefail

# cd into script folder
cd "$(dirname "$(readlink -f "${BASH_SOURCE}")")" || Die "cannot change into dir"

# the unit tests, two directories up
UTESTS="../../utests"
[[ -d "${UTESTS}" ]] || Die "no ${UTESTS} directory"

CLDR_VERSION=$(Version plurals.json _cldrVersion)       || exit 1
UNICODE_VERSION=$(Version plurals.json _unicodeVersion) || exit 1

for FILE in ordinals.json likelySubtags.json; do
	OTHER_VERSION=$(Version "${FILE}" _cldrVersion) || exit 1
	[[ "${CLDR_VERSION}" == "${OTHER_VERSION}" ]] || Die "plurals.json is CLDR ${CLDR_VERSION}, ${FILE} is CLDR ${OTHER_VERSION}"
done

# sorted by locale, then by category, like the Python version of this script did it
CARDINAL=$(Rows plurals.json  | sort -t "${SEP}" -k1,1 -k2,2) || exit 1
ORDINAL=$(Rows  ordinals.json | sort -t "${SEP}" -k1,1 -k2,2) || exit 1

{
	Preamble
	printf '// a plural rule of one language and category in the syntax of Unicode TR35.\n'
	printf '// The sample numbers of the rules are in utests/kcldr_plural_samples.h\n'
	printf 'struct KCLDRPluralRule\n{\n\tconst char* sLocale;\n\tconst char* sCategory;\n\tconst char* sText;\n};\n\n'
	printf 'constexpr const char* kCLDRVersion = "%s";\n\n' "${CLDR_VERSION}"
	RulesTable kCLDRCardinal "${CARDINAL}"
	RulesTable kCLDROrdinal  "${ORDINAL}"
} > kcldr_plurals.h.new || Die "cannot write kcldr_plurals.h.new"

mv kcldr_plurals.h.new kcldr_plurals.h || Die "cannot replace kcldr_plurals.h"

echo "kcldr_plurals.h: $(wc -l <<< "${CARDINAL}" | tr -d ' ') cardinal and $(wc -l <<< "${ORDINAL}" | tr -d ' ') ordinal rules, CLDR ${CLDR_VERSION}"

{
	Preamble
	printf '// the sample numbers CLDR gives with a plural rule of one language and category\n'
	printf '// ("@integer 1, 21, 31 ... @decimal 0.1 ..."): the unit tests check KPluralRules\n'
	printf '// against them. They live here and not with the rules in from/cldr/kcldr_plurals.h,\n'
	printf '// because the container suites build the tests from utests/ alone\n'
	printf 'struct KCLDRPluralSample\n{\n\tconst char* sLocale;\n\tconst char* sCategory;\n\tconst char* sText;\n};\n\n'
	SamplesTable kCLDRCardinal "${CARDINAL}"
	SamplesTable kCLDROrdinal  "${ORDINAL}"
} > "${UTESTS}/kcldr_plural_samples.h.new" || Die "cannot write ${UTESTS}/kcldr_plural_samples.h.new"

mv "${UTESTS}/kcldr_plural_samples.h.new" "${UTESTS}/kcldr_plural_samples.h" || Die "cannot replace ${UTESTS}/kcldr_plural_samples.h"

echo "${UTESTS}/kcldr_plural_samples.h: the samples of these rules"

# sorted by language, then by region, so that the row of the language alone comes first
SCRIPTS=$(Likely likelySubtags.json | sort -t "${SEP}" -k1,1 -k2,2) || exit 1

{
	Preamble
	printf '// the script of a language that is written in more than one script depending on\n'
	printf '// the region: one row with an empty region for the script of the language alone,\n'
	printf '// then one row per region with another script ("zh" is Hans, "zh-TW" is Hant).\n'
	printf '// Languages with one script have no rows.\n'
	printf 'struct KCLDRLikelyScript\n{\n\tconst char* sLanguage;\n\tconst char* sRegion;\n\tconst char* sScript;\n};\n\n'
	ScriptTable "${SCRIPTS}"
} > kcldr_likelysubtags.h.new || Die "cannot write kcldr_likelysubtags.h.new"

mv kcldr_likelysubtags.h.new kcldr_likelysubtags.h || Die "cannot replace kcldr_likelysubtags.h"

echo "kcldr_likelysubtags.h: $(grep -c '", "", "' kcldr_likelysubtags.h | tr -d ' ') languages with region-dependent scripts, $(grep -c '^	{ "' kcldr_likelysubtags.h | tr -d ' ') rows"
