
#pragma once

/// @file kconfiguration.h
/// library configuration at compile time of dekaf2

#define DEKAF_VERSION 2
#define DEKAF2

#define DEKAF2_USE_FOLLY_STRINGPIECE_AS_KSTRINGVIEW 1
#define DEKAF2_USE_FBSTRING_AS_KSTRING 1
#define DEKAF2_USE_OPTIMIZED_STRING_FIND 1

#define DEKAF2_ALLOW_CONVERSIONS_WITH_OLD_KSTRING
#define DEKAF2_WITH_DEPRECATED_KSTRING_MEMBER_FUNCTIONS

#ifdef DEKAF2_USE_FBSTRING_AS_KSTRING
	#define DEKAF2_DO_NOT_WARN_ABOUT_COW_STRING
#endif
