#!/bin/bash

#% buildsetup - prepare the system for a dekaf2 build
#%
#% usage: buildsetup -quiet -go
#%


# are we in test mode?
if [ "$1" = "-x" ]; then
	set -x
	shift
fi # end check test mode

setx=Synopsis
#==================
Synopsis ()
#==================
{
	awk '/^#%/ {print substr($0,3)}' "${ME_FULLPATH}"

} # Synopsis


setx=BuildSetup
#==================
BuildSetup ()
#==================
{
	# we do not care too much if the flagfile is removed
	flagfile="/tmp/installflag-dekaf2-build-setup"
	flagversion="3" 

	if [ ! -f "${flagfile}" ] || [ "$(cat ${flagfile})" != "${flagversion}" ]
	then

		[[ -z "${bQuiet}" ]] && Info "Prepare ${DISTRIB} system for dekaf2 builds"

		case "${DISTRIB}" in
			centos)
				InstallSystemPackages centos-release-scl
				InstallSystemPackages devtoolset-7 devtoolset-7-libasan-devel devtoolset-7-libubsan-devel
				;;
			rhel)
				InstallSystemPackages yum-config-manager
				sudo yum-config-manager --enable rhel-server-rhscl-7-rpms
				;;
		esac

		case "${DISTRIB}" in
			darwin)
				InstallSystemPackages cmake boost openssl@1.1 wget
				
				InstallOptionalSystemPackages doxygen graphviz libzip xz zstd brotli mariadb sqlite
				;;
			debian)
				# make sure the repo content lists are current
				sudo apt-get update -y

				InstallSystemPackages cmake libboost-all${DEVPKG} openssl libssl-dev wget git sed tar gcc \
					libz${DEVPKG} lbzip2 libbz2${DEVPKG} zlib1g-dev

				InstallOptionalSystemPackages libmariadb${DEVPKG} sqlite3 libsqlite3${DEVPKG} doxygen graphviz \
					libzip${DEVPKG} liblzma${DEVPKG} libzstd${DEVPKG} libbrotli${DEVPKG}
				;;
			*)
				InstallSystemPackages cmake boost${DEVPKG} boost-static openssl${DEVPKG} wget git sed tar gcc \
					zlib${DEVPKG} bzip2${DEVPKG}

				InstallOptionalSystemPackages mariadb${DEVPKG} sqlite${DEVPKG} doxygen graphviz libzip${DEVPKG} \
					xz${DEVPKG} libzstd${DEVPKG} brotli${DEVPKG}
				;;
		esac

		case "${DISTRIB}" in
			fedora|centos)
				# fedora-29 is just crazy to split C++ from gcc - and it appears to be the
				# only system on which you have to install ubsan and asan independently, too
				InstallSystemPackages gcc-c++ libubsan libasan
				;;
		esac

		if [[ "$BINDIR" == "aarmv2" ]]; then
#			InstallSystemPackages gcc10 gcc10-c++ gcc-c++
			InstallSystemPackages clang
		fi

		if [ "${DISTRIB}" == "centos" ] || [ "${DISTRIB}" == "rhel" ]
		then
 			# disable /bin/git replacement for now
			if [ -f "/bin/git-no-git-replacement" ]
			then
				if [ ! -f "/bin/git1.8" ]
				then
					[[ -z "${bQuiet}" ]] && Info "Making git 2.9 the default. If you need the old git, use 'git1.8'"
					mv /bin/git /bin/git1.8 || Die "cannot rename /bin/git to /bin/git1.8"
					ln -s /opt/rh/rh-git29/root/usr/bin/git /bin/git || Die "cannot symlink /opt/rh/rh-git29/root/usr/bin/git to /bin/git"
				fi
			fi

			# enable gcc 7 for the subsequent install
			source scl_source enable devtoolset-7
			# and git 2.9 as well
			# git-2.9 appears to have vanished from centos7 by now
#			source /opt/rh/rh-git29/enable
			if [ ! -d "/opt/boost" ]
			then
				# install boost from source
				${ME_ONLYPATH}/boostinstall -go || Die
			fi
		fi

		# check if the installed cmake version is fresh enough, else install from source
		${ME_ONLYPATH}/cmakeinstall -ask || Die

		echo "${flagversion}" > "${flagfile}"

		[[ -z "${bQuiet}" ]] && Info "${DISTRIB} system prepared for dekaf2 builds"

	else
		[[ -z "${bQuiet}" ]] && Info "${DISTRIB} system already prepared for dekaf2 builds"
	fi

	if [[ "${DISTRIB}" == "centos" ]] || [[ "${DISTRIB}" == "rhel" ]]
	then
		if [[ ! -z "${bQuiet}" ]]
		then
			Info "execute the following to make sure you use a modern gcc:"
			Info ""
			Info "    source scl_source enable devtoolset-7"
#			Info "    source /opt/rh/rh-git29/enable"
		fi
	fi

} # BuildSetup

#==================
setx=Main_Body
#==================

ME=$(basename "${BASH_SOURCE}")
ME_ONLYPATH="$(cd $(dirname ${BASH_SOURCE}) && pwd)"
ME_FULLPATH="$ME_ONLYPATH/$ME"
ScriptLib="${ME_ONLYPATH}/scriptlib"

[[ ! -f "${ScriptLib}" ]] && Die "Cannot check OS version, script '${ScriptLib}' not found"

source ${ScriptLib}

if [[ "$1" == "-quiet" ]]; then
	bQuiet="1"
	shift
fi

if [ "$1" != "-go" ]; then
	Synopsis
	exit 1
fi

SetupColors
GetOS

BuildSetup
