#! /bin/bash

#%
#% kport - porting utility for use from port-independent scripts and makefiles
#%
#% usage: kport <parm>
#%
#% where <parm> is:
#%   -arch    : architecture: solaris, win32, freebsd, hp10, AWS etc.
#%   -archx   : architecture (with version)
#%   bindir   : same as -archx
#%

if [[ ${1} = -x ]]; then
	set -x
	shift
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# ARCHITECTURE
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#------------+--------------------------------------+------------------------------------------------------------------------------------------------------------------------
# desired    | /etc/redhat-release                  | uname -a
#------------+--------------------------------------+------------------------------------------------------------------------------------------------------------------------
# osx        |                                      | Darwin maynard-dhcp-194-178-10-10.transperfect.com 19.6.0 Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64 x86_64
# osxm1      |                                      | a Mac running the new M1 chipset
# alinux     |                                      | Linux version 4.1.7-15.23.amzn1.x86_64 (mockbuild@gobi-build-60006) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Mon Sep 14 23:20:33 UTC 2015
# f29        | Fedora release 29 (Twenty Nine)      | Linux aws-f29 5.2.17-100.fc29.x86_64 #1 SMP Mon Sep 23 14:09:29 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
# f32        | Fedora release 32 (Thirty Two)       | Linux may-qa-fedora32-03 5.6.8-300.fc32.x86_64 #1 SMP Wed Apr 29 19:01:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
# centos64v7 | CentOS Linux release 7.7.1908 (Core) | Linux may-anleonard-apache-04 3.10.0-1062.1.2.el7.x86_64 #1 SMP Mon Sep 30 14:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
# centos64v7 | Red Hat Enterprise Linux Server release 7.6 (Maipo) | Linux may-oladm01 3.10.0-957.10.1.el7.x86_64 #1 SMP Thu Feb 7 07:12:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
#------------+--------------------------------------+------------------------------------------------------------------------------------------------------------------------
# 
case $(file /bin/ls) in
*32-bit*)
	bits=32
	;;
*64-bit*)
	bits=64
	;;
*128-bit*)
	bits=128
	;;
esac

case $(uname -m) in
*aarch64*|*arm64*)
	arch="arm"
	;;
esac

[[ -f /etc/redhat-release ]] && name=$(cat /etc/redhat-release) || name=$(uname -a)

case "$name" in
	"Darwin"*)
		distribution="osx"
		;;
	"Fedora release"*)
		# fedora is special in that we want no 'v' in between the name and version
		# so we put both into the name
		distribution=$(echo "$name" | awk '{printf ("f%d", $3)}')
		arch=""
		bits="" # <-- drop the 64 from f29, f32, etc.
		;;
	*SUSE*|*suse*)
		BIN="suse"
		;;
	*Gentoo*|*gentoo*)
		distribution="gentoo"
		;;
	*Debian*)
		distribution="debian"
		;;
	*Ubuntu*|*ubuntu*)
		distribution="ubuntu"
		;;
	FreeBSD|OpenBSD|*BSD)
		distribution="freebsd"
		;;
	*amzn*|*AMZN*) # must be before Red Hat
		version=$(cat /etc/system-release-cpe | sed -r 's,cpe:.*:amazon:.*linux:,,g' | sed -r 's,:ga,,g')
		distribution="aws"
		;;
	"CentOS Linux release"*)
		distribution="centos"
		version=$(echo "$name" | tr '.' ' ' | awk '{printf ("%d", $4)}')
		;;
	"Red Hat Enterprise Linux Server release"*)
		distribution="centos"
		version=$(echo "$name" | tr '.' ' ' | awk '{printf ("%d", $7)}')
		;;
	*)
		echo ">> dont know about arch: $name"
		exit 1
		;;
esac

BIN=${distribution}${arch}${bits}
[[ "${version}" != "" ]] && BIN="${BIN}v${version}"

case "$1" in
	-arch|-ARCH|arch|ARCH)
		echo "$BIN" | sed -e 's/v[0-9]*//' # strip version number
		;;
	-archx|-ARCHX|-bindir|-BINDIR|bindir|BINDIR)
		echo "$BIN"
		;;
	*)
		awk  '($0 ~ /^#%/) {print substr($0,3)}' $0
		exit 1
		;;
esac
