
find_path(NGHTTP2_INCLUDE_DIR NAMES nghttp2/nghttp2.h)
find_library(NGHTTP2_LIBRARY NAMES nghttp2)

if(NGHTTP2_INCLUDE_DIR AND EXISTS "${NGHTTP2_INCLUDE_DIR}/nghttp2/nghttp2ver.h")
	file(STRINGS "${NGHTTP2_INCLUDE_DIR}/nghttp2/nghttp2ver.h" NGHTTP2_HEADER_CONTENTS REGEX "#define NGHTTP2_VERSION +\"[0-9\.]+\"")
	string(REGEX REPLACE ".*#define NGHTTP2_VERSION +\"([0-9\.]+)\".*" "\\1" NGHTTP2_VERSION_STRING "${NGHTTP2_HEADER_CONTENTS}")
	set(NGHTTP2_VERSION ${NGHTTP2_VERSION_STRING})
	unset(NGHTTP2_HEADER_CONTENTS)
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(
	NGHTTP2
	HANDLE_VERSION_RANGE
	REQUIRED_VARS NGHTTP2_LIBRARY NGHTTP2_INCLUDE_DIR
	VERSION_VAR NGHTTP2_VERSION
)

if(NOT NGHTTP2_FOUND)
	unset(NGHTTP2_LIBRARY)
	unset(NGHTTP2_INCLUDE_DIR)
else()
	set(NGHTTP2_LIBRARIES "${NGHTTP2_LIBRARY}")
	set(NGHTTP2_INCLUDE_DIRS "${NGHTTP2_INCLUDE_DIR}")
endif()
