find_path(SQLITE3_INCLUDE_DIR NAMES sqlite3.h)
find_library(SQLITE3_LIBRARY NAMES sqlite3)

if(SQLITE3_INCLUDE_DIR AND EXISTS "${SQLITE3_INCLUDE_DIR}/sqlite3.h")
	file(STRINGS "${SQLITE3_INCLUDE_DIR}/sqlite3.h" SQLITE3_HEADER_CONTENTS REGEX "#define SQLITE_VERSION +\"[0-9\.]+\"")
	string(REGEX REPLACE ".*#define SQLITE_VERSION +\"([0-9\.]+)\".*" "\\1" SQLITE3_VERSION_STRING "${SQLITE3_HEADER_CONTENTS}")
	set(SQLITE3_VERSION ${SQLITE3_VERSION_STRING})
	unset(SQLITE3_HEADER_CONTENTS)
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(
	SQLite3
	HANDLE_VERSION_RANGE
	REQUIRED_VARS SQLITE3_LIBRARY SQLITE3_INCLUDE_DIR
	VERSION_VAR SQLITE3_VERSION
)

if(SQLITE3_FOUND)
	set(SQLITE3_LIBRARIES ${SQLITE3_LIBRARY})
	set(SQLITE3_INCLUDE_DIRS ${SQLITE3_INCLUDE_DIR})
else()
	unset(SQLITE3_LIBRARY)
	unset(SQLITE3_INCLUDE_DIR)
endif()

#MARK_AS_ADVANCED(SQLITE3_INCLUDE_DIRS SQLITE3_LIBRARIES)
