
find_path(NGHTTP3_INCLUDE_DIR NAMES nghttp3/nghttp3.h)
find_library(NGHTTP3_LIBRARY NAMES nghttp3)

if(NGHTTP3_INCLUDE_DIR AND EXISTS "${NGHTTP3_INCLUDE_DIR}/nghttp3/version.h")
	file(STRINGS "${NGHTTP3_INCLUDE_DIR}/nghttp3/version.h" NGHTTP3_HEADER_CONTENTS REGEX "#define NGHTTP3_VERSION +\"[0-9\.]+\"")
	string(REGEX REPLACE ".*#define NGHTTP3_VERSION +\"([0-9\.]+)\".*" "\\1" NGHTTP3_VERSION_STRING "${NGHTTP3_HEADER_CONTENTS}")
	set(NGHTTP3_VERSION ${NGHTTP3_VERSION_STRING})
	unset(NGHTTP3_HEADER_CONTENTS)
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(
	NGHTTP3
	HANDLE_VERSION_RANGE
	REQUIRED_VARS NGHTTP3_LIBRARY NGHTTP3_INCLUDE_DIR
	VERSION_VAR NGHTTP3_VERSION
)

if(NOT NGHTTP3_FOUND)
	unset(NGHTTP3_LIBRARY)
	unset(NGHTTP3_INCLUDE_DIR)
else()
	set(NGHTTP3_LIBRARIES "${NGHTTP3_LIBRARY}")
	set(NGHTTP3_INCLUDE_DIRS "${NGHTTP3_INCLUDE_DIR}")
endif()
