# dekaf2-embed-strings.cmake - embeds the string catalogs of an application
# (one JSON file per language, see KStringCatalog) into a generated header, so
# that a single binary carries its texts.
#
#   dekaf2_embed_strings(<target> <directory> [NAMESPACE <name>] [HEADER <file>])
#
# reads every <tag>.json in <directory> and generates <file> (default
# <name>.h, default namespace "strings") in the build tree, adds it to <target>
# and the generated directory to the target's include path. The header offers
#
#   namespace <name> {
#       struct EmbeddedStrings { dekaf2::KStringView sLanguage; dekaf2::KStringView sJSON; };
#       constexpr EmbeddedStrings kEmbeddedStrings[] = { { "de-DE", ... }, ... };
#       inline bool AddEmbeddedStrings(dekaf2::KStringCatalog& Catalog);
#   }
#
# The JSON is stored as a byte array, not as a string literal - MSVC limits a
# literal to 16 KB, and a catalog easily exceeds that. The header is regenerated
# when a JSON file changes; a new file needs a re-run of CMake, as the directory
# is read at configure time.
#
# This file is both the module that defines the function and the script the
# function runs at build time (cmake -P) to write the header.

if (CMAKE_SCRIPT_MODE_FILE STREQUAL CMAKE_CURRENT_LIST_FILE)

	# ---- script mode: generate the header ----
	# expects -DEMBED_OUTPUT=<header> -DEMBED_NAMESPACE=<name> -DEMBED_FILES=<file;file;...>

	if (NOT EMBED_OUTPUT OR NOT EMBED_NAMESPACE)
		message(FATAL_ERROR "dekaf2-embed-strings: EMBED_OUTPUT and EMBED_NAMESPACE are required")
	endif()

	set(header "// generated by dekaf2_embed_strings - do not edit, edit the JSON files\n")
	string(APPEND header "// languages: ")
	set(table "")
	set(first ON)

	foreach (file IN LISTS EMBED_FILES)
		get_filename_component(tag "${file}" NAME_WE)
		string(REGEX REPLACE "[^A-Za-z0-9]" "_" ident "${tag}")

		if (NOT first)
			string(APPEND header ", ")
		endif()
		set(first OFF)
		string(APPEND header "${tag}")

		# the file as '\xNN' bytes, 32 per line
		file(READ "${file}" hex HEX)
		string(LENGTH "${hex}" hexlen)
		math(EXPR size "${hexlen} / 2")
		string(REGEX REPLACE "([0-9a-f][0-9a-f])" "'\\\\x\\1'," bytes "${hex}")
		string(REGEX REPLACE "(('\\\\x[0-9a-f][0-9a-f]',){32})" "\\1\n\t" bytes "${bytes}")

		string(APPEND arrays "// ${tag}: ${size} bytes\nconstexpr char kStrings_${ident}[] =\n{\n\t${bytes}\n};\n\n")
		string(APPEND table "\t{ \"${tag}\", { detail::kStrings_${ident}, sizeof(detail::kStrings_${ident}) } },\n")
	endforeach()

	string(APPEND header "\n\n#pragma once\n\n")
	string(APPEND header "#include <dekaf2/core/strings/kstringview.h>\n")
	string(APPEND header "#include <dekaf2/util/i18n/kstringcatalog.h>\n\n")
	string(APPEND header "namespace ${EMBED_NAMESPACE} {\n\n")
	string(APPEND header "namespace detail {\n\n${arrays}} // namespace detail\n\n")
	string(APPEND header "/// one embedded language: its tag and the JSON text of its catalog\n")
	string(APPEND header "struct EmbeddedStrings\n{\n\tdekaf2::KStringView sLanguage;\n\tdekaf2::KStringView sJSON;\n};\n\n")
	string(APPEND header "constexpr EmbeddedStrings kEmbeddedStrings[] =\n{\n${table}};\n\n")
	string(APPEND header "/// adds all embedded languages to the catalog\n")
	string(APPEND header "/// @return false when a catalog had entries that were skipped\n")
	string(APPEND header "inline bool AddEmbeddedStrings(dekaf2::KStringCatalog& Catalog)\n{\n")
	string(APPEND header "\tbool bAllGood = true;\n\n")
	string(APPEND header "\tfor (const auto& Strings : kEmbeddedStrings)\n\t{\n")
	string(APPEND header "\t\tbAllGood = Catalog.AddLanguage(Strings.sLanguage, Strings.sJSON) && bAllGood;\n\t}\n\n")
	string(APPEND header "\treturn bAllGood;\n}\n\n")
	string(APPEND header "} // namespace ${EMBED_NAMESPACE}\n")

	file(WRITE "${EMBED_OUTPUT}" "${header}")

else()

	# ---- module mode: define the function ----

	set(DEKAF2_EMBED_STRINGS_SCRIPT "${CMAKE_CURRENT_LIST_FILE}")

	function(dekaf2_embed_strings target directory)
		cmake_parse_arguments(EMBED "" "NAMESPACE;HEADER" "" ${ARGN})

		if (NOT EMBED_NAMESPACE)
			set(EMBED_NAMESPACE "strings")
		endif()
		if (NOT EMBED_HEADER)
			set(EMBED_HEADER "${EMBED_NAMESPACE}.h")
		endif()

		if (NOT IS_ABSOLUTE "${directory}")
			set(directory "${CMAKE_CURRENT_SOURCE_DIR}/${directory}")
		endif()

		# the language files, read at configure time - a new file needs a re-run
		file(GLOB files CONFIGURE_DEPENDS "${directory}/*.json")

		if (NOT files)
			message(FATAL_ERROR "dekaf2_embed_strings: no *.json files in ${directory}")
		endif()

		list(SORT files)

		set(outdir "${CMAKE_CURRENT_BINARY_DIR}/dekaf2_embedded_strings")
		set(output "${outdir}/${EMBED_HEADER}")
		file(MAKE_DIRECTORY "${outdir}")

		add_custom_command(
			OUTPUT "${output}"
			COMMAND ${CMAKE_COMMAND}
				-DEMBED_OUTPUT=${output}
				-DEMBED_NAMESPACE=${EMBED_NAMESPACE}
				"-DEMBED_FILES=${files}"
				-P "${DEKAF2_EMBED_STRINGS_SCRIPT}"
			DEPENDS ${files} "${DEKAF2_EMBED_STRINGS_SCRIPT}"
			COMMENT "embedding the strings of ${directory} into ${EMBED_HEADER}"
			VERBATIM
		)

		target_sources(${target} PRIVATE "${output}")
		target_include_directories(${target} PRIVATE "${outdir}")
	endfunction()

endif()
